export const throwAnError = () => {
    throw new Error('Something went wrong.');
}